### ISSUE TITLE
issue with cilo

### ISSUE THREAD

**Issue by keithschm** [Academy-Creatio/Nov_2021_Training#1]
Having an issue with clio. Can't make it work no matter what. What am I missing?

**Comment by keithschm** [comment]
"clio : The term 'clio' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again." 

Google is no help

**Comment by kirillkrylov** [comment]
Try
```
dotnet tool install clio -g
```
