### ISSUE TITLE
Install Script fails restoring the Database.

### ISSUE THREAD

**Issue by kieronmoran** [Academy-Creatio/Nov_2021_Training#2]
I am getting an error when executing InstallCreatio.ps1 at the Database Restore command.

The error is:
pg_restore: error: could not open input file "/usr/local/db/BPMonline7184SalesEnterprise_Marketing_ServiceEnterprise.backup": No such file or directory

**Comment by kieronmoran** [comment]
[InstallCreatio Script Video.zip](https://github.com/Academy-Creatio/Nov_2021_Training/files/7545140/InstallCreatio.Script.Video.zip)

**Comment by kirillkrylov** [comment]
[Error from Here](https://github.com/Academy-Creatio/Nov_2021_Training/blob/e6157b7e1248c3443e9602dcc64965561bfc553f/Installing%20Creatio/InstallCreatio.ps1#L22)

Script assumes you have the following Directories
![image](https://user-images.githubusercontent.com/7285114/141965071-98b0d373-9946-4d0b-a4e8-0adfec3b7421.png)


![image](https://user-images.githubusercontent.com/7285114/141965130-0660514b-a3d9-4f07-b166-8fd66c302292.png)
[Line35](https://github.com/Academy-Creatio/Nov_2021_Training/blob/e6157b7e1248c3443e9602dcc64965561bfc553f/Installing%20Creatio/InstallCreatio.ps1#L35)

/usr/local/db/${dbFileName} is mounted to My Local C:\  [docker-compose](https://github.com/Academy-Creatio/Nov_2021_Training/blob/e6157b7e1248c3443e9602dcc64965561bfc553f/Installing%20Creatio/PostgresDB/docker-compose.yaml#L14)

**Comment by kieronmoran** [comment]
Thanks for the information. Have now restored the database, thank you.

I have also added this line to the script for a colleague which takes care of this copy.
  Copy-Item "C:\Build\${FolderName}\db\*" -Destination "C:\DockerCompose\Volumes\DbImages";

**Comment by kirillkrylov** [comment]
> Thanks for the information. Have now restored the database, thank you.
> 
> I have also added this line to the script for a colleague which takes care of this copy. Copy-Item "C:\Build${FolderName}\db*" -Destination "C:\DockerCompose\Volumes\DbImages";

You only need to copy once. Every time we restore a db we use the same backup file. Consider implementing as outlined here
[Copy items from Source to Destination if they don't already exist](https://stackoverflow.com/questions/25916197/copy-items-from-source-to-destination-if-they-dont-already-exist)
