### ISSUE TITLE
Loading Symbols

### ISSUE THREAD

**Issue by kieronmoran** [Academy-Creatio/Nov_2021_Training#3]
Hi,

I know that the Day 2 methods for debugging are old and not the best way but I would still like to be able to do this.

The problem I am having is that I cannot seem to be able to load the Symbols. Are there any other tricks we can use to be able to debug?

**Comment by kirillkrylov** [comment]
Follow the academy [guide](https://academy.creatio.com/docs/developer/development_tools/development_in_ms_visual_studio/development_in_ms_visual_studio#case-1189) to configure VS.

Make sure you do 
![image](https://user-images.githubusercontent.com/7285114/142402097-5aa5e2ba-1589-4b0c-bb23-a01907532def.png)

![image](https://user-images.githubusercontent.com/7285114/142402116-9445c3ea-dfb4-400e-ae5a-8e4ecf0c2dcb.png)

![image](https://user-images.githubusercontent.com/7285114/142402124-311068a9-efa2-4834-93b5-8cc52d60ec5f.png)


When you are ready to debug, start comoilation processand  **While its building** go to VS and attach to process (Ctrl+Alt+P)

**Comment by kieronmoran** [comment]
Hasn't worked unfortunately. I will try again later.

**Comment by kieronmoran** [comment]
Actually, it now seems to be working. All ii had to do was look away :-)

Thanks for your help.
